sudo: false
language: ruby
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.1.2
env:
  global:
    secure: ESLrtxwSzFWIrgSalgI/CdHzE/Zl2V7y4yGKcD48tcNh1sYN96RxzTX6tqhWbHel+tvyVV+kd+xrQF5OsckbBomdCbPsS+rMCus5KKFjPp4LUoq2VM8K17diZTHtm5bBusAqcvKtJ1drS31+s+8EVpYF5hmrtGb356uMMfUsz6U=