# Site settings
title: JK's blog
email: eshepelyk@gmail.com
description: Simple blog for some thoughts to be shared. Mostly about Java programming
baseurl: ""
url: "http://eshepelyuk.github.io" # the base hostname & protocol for your site
twitter_username: eshepelyuk
github_username:  eshepelyuk
ga: true

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=coderay

disqus_shortname: eshepelyukblog

exclude: ['Gemfile.lock', 'Gemfile', 'build.sh', '*.iml']
