# Site settings
title: JK's blog
email: eshepelyk@gmail.com
description: Simple blog for some thoughts to be shared. Mostly about Java programming
baseurl: ""
url: "http://eshepelyuk.github.io" # the base hostname & protocol for your site
twitter_username: eshepelyuk
github_username:  eshepelyuk

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=coderay

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true

disqus_shortname: eshepelyukblog

exclude: ['Gemfile.lock', 'Gemfile', 'build.sh']