# Site settings
title: JK's blog
email: eshepelyk@gmail.com
description: Simple blog for some thoughts to be shared. Mostly about Java programming
baseurl: "http://eshepelyuk.github.io"
twitter_username: eshepelyuk
github_username:  eshepelyuk

google_analytics: true

asciidoctor:
  attributes:
    - icons=font
    - hardbreaks!
    - sectanchors
    - source-highlighter=coderay

disqus_shortname: eshepelyukblog

exclude: ['README.adoc', 'Gemfile.lock', 'Gemfile', '*.sh', '*.iml', 'pdf-theme', 'EvgenyShepelyukCV.adoc']

