# Site settings
title: JK's blog
email: eshepelyk@gmail.com
description: Simple blog for some thoughts to be shared. Mostly about Java programming
baseurl: ""
url: "http://eshepelyuk.github.io" # the base hostname & protocol for your site
twitter_username: eshepelyuk
github_username:  eshepelyuk

google_analytics: true
facebook_share: false
twitter_share: false 

asciidoctor:
  attributes:
    - icons=font
    - hardbreaks!
    - source-highlighter=coderay

disqus_shortname: eshepelyukblog

exclude: ['Gemfile.lock', 'Gemfile', '*.sh', '*.iml']
