:sectnums!:
:no-header-footer:
:notitle:
:pagenums!:
:pdf-stylesdir: pdf-theme 
:pdf-style: eshepelyuk

== IEVGENII SHEPELIUK

_Software development professional, team leader and technical lead
with 15+ years experience of creating and delivering software solutions.
Concentrated on product quality and continuous improvements in all fields, 
including software development, infrastructure operations, adopting leading edge technologies,
building good team relationship and self-education. 
Agile engineering practices and development methodologies advocate. OSS enthusiast and contributor._

_Looking for opportunity of obtaining senior technical position, preferably in JVM based software project.
Interested in distributed, high-load and performance critical applications.
A major advantage will be working for a relatively small team dedicated to the project,
understanding their goals and facing or planning distinguishable technological challenges._

=== Qualification highlights

* successful development of distributed multi-layer cross-platform applications, with massive integration of external services and providers
* providing high availability and performance tuning of software solutions including web sites and standalone middleware applications
* deadline management and project completion on time including startups, legacy application migration and unfinished third-party projects
* successful transformation of development teams into self-organizing, cross-functional feature team by adopting and teaching Agile practices and DevOps culture
* hands-on worker attitude both for technical/development activities and management/business analytics activities as well
* improving and injecting QA using continuous integration, test automation and TDD / BDD
* strong communication skills, especially while managing issues between technical and non-technical team members

=== Education

* Master of computer engineering, diploma with honors. Department of computer and network systems, Chernihiv State Technological University, 1998 - 2003

=== Contacts and References

* Languages: 	Fluent English, native Ukrainian.
* Location: 	Kyiv, Ukraine  
* Mail: 		mailto:eshepelyuk@gmail.com[eshepelyuk@gmail.com]
* Skype: 	    link:skype:eshepelyuk?add[eshepelyuk]
* LinkedIn: 	https://www.linkedin.com/in/evgenyshepelyuk[https://www.linkedin.com/in/evgenyshepelyuk]
* GitHub: 	    https://github.com/eshepelyuk[https://github.com/eshepelyuk]
* Blog: 		http://eshepelyuk.github.io/[http://eshepelyuk.github.io/]

<<<

== PROFESSIONAL EXPERIENCE and PROJECT DETAILS

=== New Age Solutions Ukraine LLC

*HRZN iGaming Platform - cloud native, microservice based, reactive,
event driven iGaming platform delivering high performance and resilient products to iGaming operators,
including operational, analytical and infrastructure solutions.*

* Technologies: Microservice Architecture, Event Driven Architecture, Reactive Programming, Scala,
AKKA (actors, http, cluster, gRPC, streams), PostgreSQL, ElasticSearch, Confluent Platform,
Kafka, Alpakka Kafka, KSQL, Avro, Docker, GitOps, Kubernetes, Kubernetes operators, Helm, Terraform,
Open Policy Agent, Prometheus, Grafana, Python, Jenkins, Gradle, AWS(EC2, RDS), Gatling, Asciidoctor, PlantUML.
* Team: 4 dev teams, Data team, QA team, BA team, Infrastructure team, ~ 60 people.
* Role: Solution Architect, Software Architect, Principal Software Engineer.
* Responsibilities:
** Provide strategic input for technology investments to design, prototype and develop platform reference architecture.
** Evaluate and build microservice and event driven approaches to the product technology stack.
** Injecting DevOps culture, maximizing collaboration between business development, software development and infrastructure teams.
** Establishing SLDC for the entire platform.
** Design and improve CI/CD tools, processes and procedures.
** Create automated solutions and tools to support software and infrastructure development, release and delivery processes.
** Working closely with QA team to maintain continuous regression testing and ensure end-to-end quality.
** Helping infrastructure team to establish automated monitoring and alerting for early problem detection.
** Adopting and driving cloud native technologies, especially Kubernetes, API Gateway, ingress traffic routing etc.
** Participating in platform pre sales, creating technical proposal documentation for the clients.
** Collaborate with platform customers and business team to provide the most useful product usage options to satisfy business needs.
** Incorporating requirements and features into technical solution design.
** Evaluate options for new IT solutions and services, making emphasis on OSS products.
** Embrace OSS culture within company and help teams contributing to OSS products.

<<<

=== Infopulse Ukraine LLC

*SMS SH (DEC 2015 - FEB 2016) - SMS blacklisting and routing service for mobile operator Golan Telecom*

* Technologies: Reactive Programming, Scala, AKKA Actors, AKKA Http, REST, JMS, Apache Camel, Groovy, Gradle, Spock, JIRA, Jenkins, Docker, Cassandra
* Team: 4 developers, BA
* Role: Team Lead, Architect, Developer
* Responsibilities:
** Team Leading and customer communication tasks
** Implementing design to achieve low latency and scalability
** Throughput measurement and optimization
** Creating deployment artifacts and deployment to customer's site

*Oberthur Technologies TSM SP v5 (MAY 2013 - DEC 2015) - platform that remotely manages installation and life cycle of NFC services on secure elements (SIM cards, eSE) embedded in mobile devices, collaborating with external systems such as TSM MNO or KMS*

* Technologies: Polyglot Programming, Reactive Programming, AKKA Actors, AKKA Persistence, Scala, Java, Server Side JavaScript, Rhino, Jetty, Servlets, JSP, XML, SOAP, JAX-WS, Groovy, Gradle, Spock, JIRA, Jenkins, Docker, MariaDB, Global Platform, NFC.
* Team: 3 scrum feature teams, dedicated QA and Integration teams, business analysts, ~25 peoples.
* Role: Tech Lead, Team Lead, Developer.
* Responsibilities:
** Adoption and injection of agile engineering practices
** Implementing Global Platform Messaging and Global Platform Card specifications
** Maintain project’s reactive and polyglot programming model
** Collaborating with functional architects and business analysts on defining product architecture
** Design and implementation of technical solutions using actor concurrency model
** Supporting QA team on creating robust testing framework
** Facilitating Scrum events and supporting team with Agile processes adoption

<<<

=== Ciklum - Playtech Inc.

*WPL (OCT 2012 – APR 2013) - platform for creating online gambling web portals (as the company's product)*

* Technologies: J2SE, J2EE, Tomcat, JSON, Portlets, Liferay, MySQL, Spring, XML, JAXB, WebDriver, Groovy, Spock, Gradle, Jenkins
* Team: Backend and Frontend development teams, QA team, ~25 people.
* Role: Backend Developer, Build engineer.
* Responsibilities
** Organizing build process using Gradle, defining release flows
** Developing Liferay Portlets
** Injecting TDD practices and tools
** Collaborating with architects on defining platform components
** Support for QA and Frontend teams
** Creating end-user solutions based on WPL platform

=== SysIQ Inc. 

*Telescope.com (NOV 2011 - OCT 2012) - e-commerce portal based on OCP platform*

* Technologies: J2SE, J2EE, Tomcat, JSP, JSTL, MSSQL, Spring, XML, JAXB, WebDriver.
* Team: ~7 developers
* Role: Tech Lead, Team Lead, Developer, Agile practices coach
* Responsibilities
** Working close with local and offshore project management
** Face-to-face communication with customer representative and requirement analysis
** Architectural solution design and implementation
** Adoption and injection of Agile engineering practices
** Establishing unit, integration and functional testing of delivered product
** Coaching team member for adoption of OCP platform

<<<

=== Luxoft Eastern Europe LLC - UBS Investment Bank

*SSENG Clearing & Settlement (2009 – 2011) – Middleware and FrontEnd software for stock exchange market,
providing means to process, clear and settle stock exchange trades, manage their lifecycle and gather reports*

* Technologies: J2EE, RMI, AOP, Spring, JMS, Oracle, GWT, GXT, AJAX, JSON, Groovy, Grails, WebDriver, Junit, Hibernate.
* Team: 10 distributed scrum teams of ~10 engineers each, PO team consisting of business analysts and subject matter experts, global production support team.
* Role: Scrum Master, Team Coordinator, Software Architect and Developer
* Responsibilities
** Scrum process facilitation and coaching
** Architectural solution design and implementation
** Unit, integration and functional testing. TDD/BDD/ADD adopting and coaching
** Face-to-face communication with customer and requirement analysis
** Communication and demonstration of developed software to end-users
** Maintaining continuous integration
** Release preparation and delivery support

=== Soft Industry LLC  (2003 - 2009)

Roles: Team Lead, Developer, Build Engineer, Tech Lead, Architect.

Various projects, including:

* FreedomInput.com (2008 – 2009) – Bluetooth Keyboard driver, Freedom Keychain GPS 2000 driver
and GPS software for BlackBerry phones.
* Video Streaming Server and Visualization (AUG 2009 – OCT 2009) -
HTTP proxy solution for online video to increase logical bandwidth and number of clients bandwidth using proxying of streams.
* RDT600 (AUG 2008 – MAY 2009) - Hardware monitoring and visualization tool RDT600 for SICK AG.
* Eset.ua (MAY 2007 – SEP 2008) – Business and financial management system
for Ukraine branch of ESET company. Distributed peer networking application for distribution files required for ESET company products.
* Prydbay.com (JAN 2007 – DEC 2009) – Online Store of communication topups and online games.
Processing and billing layer for different payment systems to provide uniform interface for e-shops
and similar projects.
* Cloncom.com (JAN 2005 – DEC 2008) – E-commerce solution for selling electronic communications topups,
related services and products. High performing RESTful API service providing cached product catalog. Legacy platform rewrite.
* AAA (JAN 2004 – JUN 2004) - Billing and network traffic accounting system.
* Mobile Games server (AUG 2003 – DEC 2003).
* Newsletter engine (FEB 2003 – JUN 2003) – Corporate offline messaging exchange system.
