---
tags:
- coffeescript
- coding dojo
- kata
excerpt: false
---
:linkattrs:
= CodingDojoCnUa #6

Today, 28th of July, our CodingDojoCnUa community successfully conducted 6th Coding Dojo. 
We met at Chernihiv's office of SysIQ, as few times before. 
The subject of our session was `RomanNumerals` kata - description can be found by http://codingdojo.org/cgi-bin/wiki.pl?KataRomanNumerals[HERE]. 
Main thing distinguishing this Dojo from previous ones was splitting the attendees into two separate teams 
that were working on their own without shared _Design Session_. 
Each team was responsible for figuring out own implementation and eventually produced working code together with unit tests. 
Both implementation can be found at GitHub

* https://github.com/eshepelyuk/CodingDojoCnUa/tree/master/Dojo6/teamA[Code for TeamA, window='_blank']
* https://github.com/eshepelyuk/CodingDojoCnUa/tree/master/Dojo6/teamB[Code for TeamB, window='_blank']

== What we've discovered

First things to mention that team provided completely different solutions to the same problem. 
Relative simplicity of Kata seemed to help coders to split task into smaller parts thus supporting true incremental development, 
concentrating on providing small slices of functionality after creating failed test. 
Unlike previous times there were no attempts to create `God Functions` immediately after start of Dojo. 
Although longer Design Sessions are essential to make team move faster and effectively with incremental development.

Second main observation is that few peoples who don't use TDD on daily basis realized that this approach 
could significantly affect original design of algorithm and even imposes final design. 
On retrospective meeting one of us described this impression  

[quote]
People saw TDD in action.

3rd and the shortest - `CoffeeScript` tastes better each time you try it :)

== What we're gonna try next time ? 

Apparently largest negative issue raised on retro was isolation of members within own team and lack of inter-team communication. 
Attendees suggested various options, even tackle more complicated task than kata, 
like some sort of network game, and go through complete process of application development.

But finally we agreed on just to exchange team members in the middle of next Dojo 
to see if this is helpful for coding and / or brings more fun to the event :)

Some photos http://www.facebook.com/media/set/?set=oa.378960365504429&amp;type=1[@Facebook, window='_blank']