---
tags:
- windows
- docker
- microservice
- sdkman
- gradle
- groovy
excerpt: |
  Continuation of `Windows` and `Docker` integration guide.
  The goal of this post is to show quick and easy way of creating new `JVM` project and run it as a `Docker` container on `Windows`.
---

= JVM microservices - JVM based application running in Docker container

Continuation of `Windows` and `Docker` integration guide.
The goal of this post is to show quick and easy way of creating new `JVM` project and run it as a `Docker` container on `Windows`.

In the http://eshepelyuk.github.io/2015/11/26/jvm-microservice-docker-windows.html[previous post] I've described how to setup `Docker` environment on `Windows` powered PC and run existing `Docker` container.
Now it's time to create own `JVM` project, create `Docker` image and run it.

When it comes to quickly prototype something on `JVM` platform - `Groovy` is a great language choice.
Furthermore, using `Groovy` in this guide is a perfect example of `Docker` powered `JVM` microservices polyglot nature. For a build tool my natural choice is `Gradle`, that will be used in this guide as well.


== Setup Gradle using sdkman

`Gradle` can be installed and added to `PATH` manually, but there exists `sdkman` tool that drastically simplifies installation of `Gradle` and other utilities.
So, I'd suggest to spend some minutes to setup it and use for `Gradle` installation.

. First of all `unzip` should be installed, since it is required for `sdkman` installer. 
In new `bash` console execute.
  
 $ pacman -S unzip

. Follow instructions from http://sdkman.io/install.html[sdkman site^] to install the tool.

. After the installation there can be issues running `sdkman` in `msys2` environment. 
The reason is explained in corresponding https://github.com/sdkman/sdkman-cli/pull/384[GitHub Issue]

.. To fix it open file `~/.sdkman/bin/sdkman-init.sh` and find the line.

 if [[ -n "${CANDIDATE_NAME}" && -h "${CANDIDATE_DIR}" ]]; then

.. Replace it with.
 
 if [[ -n "${CANDIDATE_NAME}" && -d "${CANDIDATE_DIR}" ]]; then

. Now `sdkman` is ready, open new `bash` console and install latest `Gradle` version.
  
 $ sdk install gradle

. Check that `Gradle` was installed correctly (may require opening new `bash`).

[source]
----
$ gradle --version

------------------------------------------------------------
Gradle 2.9
------------------------------------------------------------

Build time:   2015-11-17 07:02:17 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 8.1 6.3 amd64
----

== Sample Groovy application

. Project folder structure can be generated by running `Gradle` task.

 $ gradle init --type groovy-library

. After generation `Library.groovy` and `LibraryTest.groovy` could be removed.

. https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper] is generated during `gradle init` and only wrapper will be used onward in this guide.

. Create main application class.
+
[source,groovy]
.ua.eshepelyuk.blog.Hello.groovy
----
package ua.eshepelyuk.blog

println "Hello from Docker by Groovy and Gradle" <1>
----
<1> declaration of `public static void main` could be omitted in `Groovy`

== Enable Docker support for project build script

There's no need to deal with `Dockerfile` and related things for creating `Docker` for `Gradle` based project.
_There're plugins for this :))_

Enable plugins::
+
[source,groovy]
----
plugins {
    id 'groovy' 
    id 'application' <1>
    id 'com.bmuschko.docker-java-application' version '2.6.1' <2>
}
----
<1> https://docs.gradle.org/current/userguide/application_plugin.html[Plugin] for building _application_ that can be embedded in `Docker` image
<2> https://github.com/bmuschko/gradle-docker-plugin[Docker support plugin]

Customize plugins::
+
[source,groovy]
----
mainClassName = 'ua.eshepelyuk.blog.Hello' <1>

docker {
    url = "https://192.168.99.100:2376" <2>
    javaApplication {
        tag = "eshepelyuk/hellodockergradle:latest" <3>
    }
}
----
<1> Entry point for `application` plugin
<2> Result of `docker-machine url default` command, `tcp` must be replaced to `https`
<3> `Docker` image tag name

== Build image and run Docker container

. Execute command to create `Docker` image.
 
 $ ./gradlew dockerBuildImage

. Check new image is available by running `docker image`.
Command output should include new image tagged with `eshepelyuk/hellodockergradle` (setting from `build.gradle`).
+
----
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED                  VIRTUAL SIZE
..
eshepelyuk/hellodockergradle   latest              daa12bd8bb4f        About a minute ago   649 MB
..
----

. Start container using `docker run` and inspect the output to match expected from `Hello.groovy` class.
+
----
$ docker run eshepelyuk/hellodockergradle
Hello from Docker by Groovy and Gradle
----

NOTE: Full project's code is available at https://github.com/eshepelyuk/CodeForBlog/tree/master/HelloDockerGradle[My GitHub^]
