---
tags:
- windows
- docker
- microservice
- sdkman
- gradle
- groovy
excerpt: |
  JVM microservices - Create JVM based app running in Docker container
---

= JVM microservices - Create JVM based app running in Docker container

Continuation of previous post aboout `Windows` and `Docker` integration.
The goal is to show quick and easy way of creating sample `Java` project and run it as a `Docker` container.

`Gradle` and `Groovy` will be used.
`SDKMAN` is a great tool.

== Setup Gradle using SDKMAN

. First of all `unzip` should be installed to as it is required for `SDKMAN`. 
In new `bash` console execute
  
 $ pacman -S unzip

. Follow instructions from http://sdkman.io/install.html[SDKMAN site^] to install the utility

. After the installation there can be a problems running `SDKMAN` in `msys2` environment. 
Corresponding https://github.com/sdkman/sdkman-cli/pull/384[GitHub Issue]

.. To fix it open file `~/.sdkman/bin/sdkman-init.sh` and find line

  	if [[ -n "${CANDIDATE_NAME}" && -h "${CANDIDATE_DIR}" ]]; then

.. Replace it with
 
  	if [[ -n "${CANDIDATE_NAME}" && -d "${CANDIDATE_DIR}" ]]; then

. Install latest `Gradle` version
  
 $ sdk install gradle

. Open new console and check that `Gradle` was installed correctly

[source]
----
$ gradle --version

------------------------------------------------------------
Gradle 2.9
------------------------------------------------------------

Build time:   2015-11-17 07:02:17 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 8.1 6.3 amd64
----

== Generate sample Groovy application

. Project folder structure can be created by `Gradle` itself 

 $ gradle init --type groovy-library

. Generated `Library.groovy` and `LibraryTest.groovy` could be removed

. https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper] is generated and it will be used onward in this guide.

. Create main application class
+
[source,groovy]
.ua.eshepelyuk.blog.Hello.groovy
----
package ua.eshepelyuk.blog

println "Hello from Docker by Groovy and Gradle" <1>
----
<1> declaration of `public static void main` can be omitted in `Groovy`

== Enable Docker support for JVM application

Gradle plugin https://github.com/bmuschko/gradle-docker-plugin

. Enable plugin
+
[source,groovy]
----
apply plugin: 'groovy'
apply plugin: 'application'
apply plugin: 'com.bmuschko.docker-java-application'

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.bmuschko:gradle-docker-plugin:2.6.1"
    }
}

----

. qwe
+
[source,groovy]
----
mainClassName = 'ua.eshepelyuk.blog.Hello' <1>

docker {
    url = "https://192.168.99.100:2376" <2>
    javaApplication {
        maintainer = 'Evgeny Shepelyuk "eshepelyuk@gmail.com"'
        tag = "${project.group}/${applicationName.toLowerCase()}:latest" <3>
    }
}
----
<1> 1
<2> 2
<3> 3

== Build and run Docker image

. To create `Docker` image execute
 
 $ ./gradlew dockerBuildImage

. Check new image is available
 
 $ docker images

. Output should include our image `ua.eshepelyuk/hellodockergradle`
+
----
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED                  VIRTUAL SIZE
................
ua.eshepelyuk/hellodockergradle   latest              451f610b25cc        Less than a second ago   649 MB
...............
----

. Start container by running and inspect the output
----
$ docker run ua.eshepelyuk/hellodockergradle
Hello from Docker by Groovy and Gradle
----
